IF NOT EXISTS ( SELECT  *
                FROM    sys.schemas
                WHERE   name = 'OVERSTATS' )
    EXEC('CREATE SCHEMA OVERSTATS');
GO

DROP TABLE IF EXISTS OVERSTATS.SINGLEMAP, OVERSTATS.MULTIMAP, OVERSTATS.STATS,OVERSTATS.MAP, OVERSTATS.HERO, OVERSTATS.RANK, OVERSTATS.FRIENDS, OVERSTATS.PLAYER; 

CREATE TABLE OVERSTATS.PLAYER (
    id INTEGER PRIMARY KEY ,
    nome VARCHAR(50)  NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    main VARCHAR(20),
);

CREATE TABLE OVERSTATS.FRIENDS (
    player1 INTEGER NOT NULL,
    player2 INTEGER NOT NULL,
    PRIMARY KEY (player1, player2),
    FOREIGN KEY (player1) REFERENCES OVERSTATS.PLAYER(id),
    FOREIGN KEY (player2) REFERENCES OVERSTATS.PLAYER(id)
);

CREATE TABLE OVERSTATS.RANK (
    player INTEGER NOT NULL,
    teamrole VARCHAR(20) NOT NULL,
    nome VARCHAR(20) NULL,
    PRIMARY KEY (player, teamrole),
    FOREIGN KEY (player) REFERENCES OVERSTATS.PLAYER(id)
);

CREATE TABLE OVERSTATS.HERO (
    nome VARCHAR(50) NOT NULL,
    teamrole VARCHAR(50) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    shortdescription VARCHAR(250) NOT NULL,
    hability1 VARCHAR(50) NOT NULL,
    hability2 VARCHAR(50) NOT NULL,
    PRIMARY KEY (nome)
);

CREATE TABLE OVERSTATS.MAP (
    nome VARCHAR(50) NOT NULL,
    gameMode VARCHAR(50) NOT NULL,
    located VARCHAR(50) NOT NULL,
    PRIMARY KEY (nome)
);

CREATE TABLE OVERSTATS.STATS (
    stat_id INTEGER PRIMARY KEY IDENTITY,
    player INTEGER NOT NULL,
    hero VARCHAR(50) NULL,
    kda INTEGER NOT NULL,
    accuracy INTEGER NOT NULL,
    result VARCHAR(10) NOT NULL,
    time_played INTEGER NOT NULL,
    map VARCHAR(50) NOT NULL,
    FOREIGN KEY (player) REFERENCES OVERSTATS.PLAYER(id),
    FOREIGN KEY (hero) REFERENCES OVERSTATS.HERO(nome),
    FOREIGN KEY (map) REFERENCES OVERSTATS.MAP(nome)
);


CREATE TABLE OVERSTATS.MULTIMAP (
    nome VARCHAR(50) NOT NULL,
    map1 VARCHAR(50) NOT NULL,
    map2 VARCHAR(50) NOT NULL,
    map3 VARCHAR(50) NOT NULL,
    PRIMARY KEY (nome),
    FOREIGN KEY (nome) REFERENCES OVERSTATS.MAP (nome)
);

CREATE TABLE OVERSTATS.SINGLEMAP (
    nome VARCHAR(50) NOT NULL,
    cartType VARCHAR(50) NOT NULL,
    PRIMARY KEY (nome),
    FOREIGN KEY (nome) REFERENCES OVERSTATS.MAP (nome)
);
